# Generated by Django 4.1.5 on 2023-01-02 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentTvShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('choice_show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_object', to='book.book')),
            ],
        ),
    ]
