# Generated by Django 4.1.5 on 2023-01-02 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_expert'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation', models.TextField()),
                ('choice_show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_recommendation', to='book.book')),
                ('name_expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.expert')),
            ],
        ),
    ]
